name: data_platform
version: "0.1.0"
config-version: 2
require-dbt-version: [">=1.7.0", "<2.0.0"]

profile: data_platform

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  data_platform:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table
    marts_derivations:
      +materialized: table
    marts_derivation_lineage:
      +materialized: table
