"""Provider-neutral source catalog and canonical mapping registry."""

from data_platform.provider_catalog.registry import (
    CANONICAL_DATASETS,
    FUTURE_PROVIDER_TARGETS,
    PROVIDER_MAPPINGS,
    PROMOTION_CANDIDATE_MAPPINGS,
    RECONCILIATION_REQUIRED_METRICS,
    TUSHARE_INTERFACE_REGISTRY,
    AmbiguousProviderInterface,
    CanonicalDataset,
    CanonicalField,
    ProviderDatasetMapping,
    SourceInterface,
    TushareInterfaceRegistryEntry,
    build_tushare_interface_registry,
    catalog_summary,
    load_tushare_provider_catalog,
    mapping_for_provider_interface,
    mapping_for_source_interface_id,
    tushare_interface_metadata_for_raw_dataset,
)

__all__ = [
    "CANONICAL_DATASETS",
    "FUTURE_PROVIDER_TARGETS",
    "PROVIDER_MAPPINGS",
    "PROMOTION_CANDIDATE_MAPPINGS",
    "RECONCILIATION_REQUIRED_METRICS",
    "TUSHARE_INTERFACE_REGISTRY",
    "AmbiguousProviderInterface",
    "CanonicalDataset",
    "CanonicalField",
    "ProviderDatasetMapping",
    "SourceInterface",
    "TushareInterfaceRegistryEntry",
    "build_tushare_interface_registry",
    "catalog_summary",
    "load_tushare_provider_catalog",
    "mapping_for_provider_interface",
    "mapping_for_source_interface_id",
    "tushare_interface_metadata_for_raw_dataset",
]
