"""Per-company injection audit — three-layer coverage view.

MVP20 has three orthogonal data layers contributing dp_ids to a company:

1. **overlay schema (LLM-derived, ~33 slots per company)** — the per-company
   stock overlay generated by Codex/LLM (``company_node_instance``). These
   slots are ``Unknown`` until LLM/codex fills them; sources cannot.
2. **realtime SQLite (Tushare / FMP / Futu / akshare, ~25-60 dp_ids)** —
   what data sources have actually injected into ``realtime_current``.
   Disjoint from overlay schema by design.
3. **industry L0 inherit (industry overlays, 5-14 dp_ids per industry)** —
   ``L0.*`` rows from ``config/industry_overlays/{industry}.yaml`` that the
   company effectively inherits as part of its primary industry. These are
   filled at the industry level (one row per industry × period), not per
   stock, so they don't appear in ``company_node_instance`` but still count
   toward a stock's effective data coverage.

The audit produces a 3-layer breakdown so users can see at a glance which
layer is responsible for the remaining "Unknown" gap toward the spec's 250
canonical dp_ids.

Used by the ``mvp20 audit-injection`` CLI to produce
``docs/audit/injection_audit.md`` after a ``collector --source real`` cycle.
"""

from __future__ import annotations

import csv
import json
import re
import sqlite3
from dataclasses import dataclass, field
from pathlib import Path

# Total dp_ids in spec's canonical taxonomy (§ coverage_audit.md Section 7).
SPEC_TOTAL_DP_IDS = 250


@dataclass
class CompanyAudit:
    """Three-layer coverage for one company.

    ``industry_ids`` is the full set (from universe.yaml), while
    ``industry_id`` remains the primary industry for back-compat.
    """

    ts_code: str
    industry_id: str               # primary industry (back-compat)
    industry_ids: list[str]        # all industries this company belongs to
    name: str | None
    market: str                    # A / HK / US

    # --- Layer 1: overlay schema (per-company, LLM-derived) -----------------
    overlay_total: int = 0         # rows in company_node_instance (typically 33)
    overlay_known: int = 0         # data_status=Known
    overlay_optionality: int = 0   # data_status=Optionality
    overlay_unknown_real: int = 0  # data_status=Unknown
    overlay_inactive: int = 0      # data_status=Inactive
    overlay_na: int = 0            # data_status=NA or NULL
    overlay_dp_ids: list[str] = field(default_factory=list)
    overlay_known_dp_ids: list[str] = field(default_factory=list)
    overlay_opt_dp_ids: list[str] = field(default_factory=list)

    # --- Layer 2: realtime SQLite (data-source injected) --------------------
    realtime_dps: int = 0          # distinct dp_ids in realtime_current
    realtime_dp_ids: list[str] = field(default_factory=list)
    realtime_by_source: dict[str, int] = field(default_factory=dict)
    realtime_ages: list[int] = field(default_factory=list)

    # --- Layer 3: L0 inherit (industry-level Known L0 dp_ids) ---------------
    industry_l0_known: int = 0
    industry_l0_dp_ids: list[str] = field(default_factory=list)

    # --- Effective coverage = union of all three layers ---------------------
    spec_total: int = SPEC_TOTAL_DP_IDS
    effective_dps: int = 0         # |union(overlay K/Opt, realtime, L0 Known)|
    effective_dp_ids: list[str] = field(default_factory=list)
    coverage_pct: float = 0.0      # effective_dps / spec_total * 100

    # --- Back-compat aliases (kept so old CSV/MD readers don't break) ------
    @property
    def schema_dp_ids(self) -> list[str]:
        return self.overlay_dp_ids

    @property
    def schema_filled(self) -> list[str]:
        # "filled" historically meant overlay_dp_ids that also appeared in
        # realtime; with the new architecture this is structurally empty,
        # but we keep the alias to avoid breaking any external readers.
        rt = set(self.realtime_dp_ids)
        return sorted(set(self.overlay_dp_ids) & rt)

    @property
    def sources(self) -> dict[str, int]:
        return self.realtime_by_source


def _market_of(ts_code: str) -> str:
    if ts_code.endswith((".SH", ".SZ", ".BJ")):
        return "A"
    if ts_code.endswith(".HK"):
        return "HK"
    if ts_code.endswith(".US"):
        return "US"
    return "?"


def _load_industry_l0_known(
    industry_overlays_dir: Path,
) -> dict[str, list[str]]:
    """Walk ``config/industry_overlays/*.yaml`` and return
    ``{industry_id: [known_l0_dp_ids]}``.

    A node counts as "L0 inherit" if it has a ``dp_id``, ``data_status``
    is ``Known``, and ``layer`` starts with ``industry`` (the industry
    overlay layers ``industry_macro/supply/price/cost/competition`` all
    map to L0/L1 in the spec).
    """

    out: dict[str, list[str]] = {}
    if not industry_overlays_dir.exists():
        return out
    try:
        import yaml as _yaml
    except ImportError:
        return out
    for path in sorted(industry_overlays_dir.glob("*.yaml")):
        try:
            data = _yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        except Exception:
            continue
        industry_id = data.get("industry_id") or path.stem
        known: list[str] = []
        for n in data.get("nodes") or []:
            if not isinstance(n, dict):
                continue
            dp_id = n.get("dp_id")
            status = n.get("data_status")
            layer = str(n.get("layer") or "")
            if dp_id and status == "Known" and layer.startswith("industry"):
                known.append(str(dp_id))
        out[industry_id] = sorted(set(known))
    return out


def _load_spec_dp_ids(coverage_audit_path: Path) -> set[str]:
    """Parse ``docs/data_sources/coverage_audit.md`` Section 7 and return
    the canonical 256 dp_ids. Falls back to an empty set if the file is
    missing (callers should still set ``spec_total=SPEC_TOTAL_DP_IDS``)."""

    if not coverage_audit_path.exists():
        return set()
    try:
        text = coverage_audit_path.read_text(encoding="utf-8")
    except Exception:
        return set()
    # Match `| `dp.id` |` lines inside Section 7 only.
    out: set[str] = set()
    in_section = False
    for line in text.splitlines():
        if line.startswith("## 7"):
            in_section = True
            continue
        if in_section and line.startswith("## "):
            break
        if not in_section:
            continue
        m = re.match(r"\|\s*`([^`]+)`", line)
        if m:
            out.add(m.group(1))
    return out


def collect_audit(
    db_path: Path,
    universe_path: Path | None = None,
    industry_overlays_dir: Path | None = None,
    coverage_audit_path: Path | None = None,
) -> tuple[list[CompanyAudit], dict]:
    """Walk every primary-industry overlay and compute three-layer coverage.

    Returns (per-company list, global summary).
    """

    if universe_path is None:
        universe_path = Path("config/mvp20.universe.yaml")
    if industry_overlays_dir is None:
        industry_overlays_dir = Path("config/industry_overlays")
    if coverage_audit_path is None:
        coverage_audit_path = Path("docs/data_sources/coverage_audit.md")

    # --- universe.yaml (name + industry_ids) --------------------------------
    name_by_ts: dict[str, str] = {}
    industry_ids_by_ts: dict[str, list[str]] = {}
    if universe_path.exists():
        try:
            import yaml as _yaml
            data = _yaml.safe_load(universe_path.read_text(encoding="utf-8")) or {}
            for c in data.get("constituents") or []:
                ts = c.get("ts_code")
                if not ts:
                    continue
                name_by_ts[ts] = c.get("name") or ""
                ids = c.get("industry_ids") or []
                if isinstance(ids, list):
                    industry_ids_by_ts[ts] = [str(i) for i in ids]
        except Exception:
            pass

    # --- industry overlays L0 Known map -------------------------------------
    industry_l0_known_map = _load_industry_l0_known(industry_overlays_dir)

    # --- spec 256 dp_ids ----------------------------------------------------
    spec_dp_ids = _load_spec_dp_ids(coverage_audit_path)
    spec_total = len(spec_dp_ids) if spec_dp_ids else SPEC_TOTAL_DP_IDS

    # --- DB walk ------------------------------------------------------------
    conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    conn.row_factory = sqlite3.Row
    try:
        manifest_rows = conn.execute(
            """
            SELECT ts_code, industry_id
              FROM overlay_manifest
             WHERE primary_industry = 1
             ORDER BY ts_code
            """
        ).fetchall()

        # (ts_code, industry_id) -> list of (dp_id, data_status)
        schema_by_company: dict[tuple[str, str], list[tuple[str, str | None]]] = {}
        for row in conn.execute(
            """
            SELECT ts_code, industry_id, dp_id, data_status
              FROM company_node_instance
             WHERE dp_id IS NOT NULL
            """
        ).fetchall():
            schema_by_company.setdefault(
                (row["ts_code"], row["industry_id"]), []
            ).append((row["dp_id"], row["data_status"]))

        # ts_code -> list of realtime_current rows
        rt_by_company: dict[str, list[sqlite3.Row]] = {}
        for row in conn.execute(
            """
            SELECT ts_code, dp_id, source, updated_at, value_json
              FROM realtime_current
            """
        ).fetchall():
            rt_by_company.setdefault(row["ts_code"], []).append(row)

        audits: list[CompanyAudit] = []
        import time as _time
        now = int(_time.time())

        for m in manifest_rows:
            ts_code = m["ts_code"]
            industry_id = m["industry_id"]

            # --- overlay layer ---------------------------------------------
            schema_rows = schema_by_company.get((ts_code, industry_id), [])
            overlay_dp_ids = sorted({r[0] for r in schema_rows})
            known_set: set[str] = set()
            opt_set: set[str] = set()
            unknown_real = inactive = na = 0
            for dp_id, status in schema_rows:
                if status == "Known":
                    known_set.add(dp_id)
                elif status == "Optionality":
                    opt_set.add(dp_id)
                elif status == "Unknown":
                    unknown_real += 1
                elif status == "Inactive":
                    inactive += 1
                else:
                    na += 1

            # --- realtime layer --------------------------------------------
            rt_rows = rt_by_company.get(ts_code, [])
            rt_dp_set: set[str] = set()
            sources: dict[str, int] = {}
            ages: list[int] = []
            for r in rt_rows:
                rt_dp_set.add(r["dp_id"])
                src = r["source"] or "unknown"
                sources[src] = sources.get(src, 0) + 1
                if r["updated_at"]:
                    ages.append(now - r["updated_at"])

            # --- L0 inherit layer (from industry overlay) ------------------
            industries = industry_ids_by_ts.get(ts_code) or [industry_id]
            l0_set: set[str] = set()
            for ind in industries:
                for dp in industry_l0_known_map.get(ind, ()):
                    l0_set.add(dp)

            # --- effective union -------------------------------------------
            effective_set = known_set | opt_set | rt_dp_set | l0_set
            coverage_pct = (
                100.0 * len(effective_set) / spec_total
                if spec_total else 0.0
            )

            audits.append(CompanyAudit(
                ts_code=ts_code,
                industry_id=industry_id,
                industry_ids=industries,
                name=name_by_ts.get(ts_code),
                market=_market_of(ts_code),
                overlay_total=len(overlay_dp_ids),
                overlay_known=len(known_set),
                overlay_optionality=len(opt_set),
                overlay_unknown_real=unknown_real,
                overlay_inactive=inactive,
                overlay_na=na,
                overlay_dp_ids=overlay_dp_ids,
                overlay_known_dp_ids=sorted(known_set),
                overlay_opt_dp_ids=sorted(opt_set),
                realtime_dps=len(rt_dp_set),
                realtime_dp_ids=sorted(rt_dp_set),
                realtime_by_source=sources,
                realtime_ages=ages,
                industry_l0_known=len(l0_set),
                industry_l0_dp_ids=sorted(l0_set),
                spec_total=spec_total,
                effective_dps=len(effective_set),
                effective_dp_ids=sorted(effective_set),
                coverage_pct=coverage_pct,
            ))

        # --- global summary -------------------------------------------------
        total = len(audits)
        by_market: dict[str, list[CompanyAudit]] = {"A": [], "HK": [], "US": [], "?": []}
        for a in audits:
            by_market[a.market].append(a)

        # Distribution buckets
        buckets = {"ge_50": 0, "ge_40": 0, "ge_30": 0, "ge_20": 0, "lt_20": 0}
        for a in audits:
            if a.effective_dps >= 50:
                buckets["ge_50"] += 1
            elif a.effective_dps >= 40:
                buckets["ge_40"] += 1
            elif a.effective_dps >= 30:
                buckets["ge_30"] += 1
            elif a.effective_dps >= 20:
                buckets["ge_20"] += 1
            else:
                buckets["lt_20"] += 1

        # Per-industry rollup
        by_industry: dict[str, list[CompanyAudit]] = {}
        for a in audits:
            by_industry.setdefault(a.industry_id, []).append(a)

        industry_rollup: list[dict] = []
        for ind, members in sorted(by_industry.items()):
            n = len(members)
            avg_overlay_k = sum(m.overlay_known for m in members) / n
            avg_overlay_opt = sum(m.overlay_optionality for m in members) / n
            avg_rt = sum(m.realtime_dps for m in members) / n
            avg_l0 = sum(m.industry_l0_known for m in members) / n
            avg_eff = sum(m.effective_dps for m in members) / n
            best = max(members, key=lambda x: x.effective_dps)
            worst = min(members, key=lambda x: x.effective_dps)
            industry_rollup.append({
                "industry_id": ind,
                "stocks": n,
                "avg_overlay_known": avg_overlay_k,
                "avg_overlay_opt": avg_overlay_opt,
                "avg_realtime": avg_rt,
                "avg_l0_inherit": avg_l0,
                "avg_effective": avg_eff,
                "best_ts": best.ts_code,
                "best_effective": best.effective_dps,
                "worst_ts": worst.ts_code,
                "worst_effective": worst.effective_dps,
            })

        # Source rollup (across all companies)
        source_rollup: dict[str, dict] = {}
        for a in audits:
            # We have (source -> row count) per company, but for unique-dp
            # we'd need to walk realtime_current grouped by source. Do it
            # in one query.
            pass
        for row in conn.execute(
            """
            SELECT source, COUNT(*) AS rows, COUNT(DISTINCT dp_id) AS dps,
                   MIN(dp_id) AS example
              FROM realtime_current
             GROUP BY source
             ORDER BY rows DESC
            """
        ).fetchall():
            source_rollup[row["source"]] = {
                "rows": row["rows"],
                "unique_dp_ids": row["dps"],
                "example": row["example"],
            }

        summary = {
            "total_companies": total,
            "spec_total": spec_total,
            "with_any_realtime": sum(1 for a in audits if a.realtime_dps),
            "with_zero_realtime": sum(1 for a in audits if not a.realtime_dps),
            "by_market": {m: len(v) for m, v in by_market.items()},
            "by_market_filled": {
                m: sum(1 for a in v if a.realtime_dps) for m, v in by_market.items()
            },
            "avg_overlay_known": (
                sum(a.overlay_known for a in audits) / total if total else 0
            ),
            "avg_overlay_opt": (
                sum(a.overlay_optionality for a in audits) / total if total else 0
            ),
            "avg_realtime": (
                sum(a.realtime_dps for a in audits) / total if total else 0
            ),
            "avg_l0_inherit": (
                sum(a.industry_l0_known for a in audits) / total if total else 0
            ),
            "avg_effective": (
                sum(a.effective_dps for a in audits) / total if total else 0
            ),
            "avg_coverage_pct": (
                sum(a.coverage_pct for a in audits) / total if total else 0
            ),
            # back-compat (preserve old `avg_realtime_per_company` name too)
            "avg_realtime_per_company": (
                sum(a.realtime_dps for a in audits) / total if total else 0
            ),
            "buckets": buckets,
            "industry_rollup": industry_rollup,
            "source_rollup": source_rollup,
            "all_schema_dp_ids": sorted(
                {d for a in audits for d in a.overlay_dp_ids}
            ),
            "all_realtime_dp_ids": sorted(
                {d for a in audits for d in a.realtime_dp_ids}
            ),
            "all_l0_inherit_dp_ids": sorted(
                {d for a in audits for d in a.industry_l0_dp_ids}
            ),
        }
        return audits, summary
    finally:
        conn.close()


# ---------------------------------------------------------------------------
# Report writers
# ---------------------------------------------------------------------------


def write_markdown(
    audits: list[CompanyAudit],
    summary: dict,
    out_path: Path,
    detailed: bool = False,
) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = []
    lines.append("# Injection Audit Report")
    lines.append("")
    lines.append(
        "> 三层数据架构覆盖度：overlay (LLM 衍生 schema, per-stock) + "
        "realtime (Tushare/FMP/Futu/akshare 灌入, per-stock) + "
        "L0 inherit (行业 overlay 共享, per-industry)。"
    )
    lines.append(
        "> Spec 总 dp_id 数 = "
        f"**{summary['spec_total']}**（来源：`docs/data_sources/coverage_audit.md` § 7）。"
    )
    lines.append("")

    total = summary["total_companies"]
    spec_total = summary["spec_total"]

    # === Summary ============================================================
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Total companies: **{total}**")
    if total:
        lines.append(
            f"- Average effective dp_ids: **{summary['avg_effective']:.1f} / "
            f"{spec_total}** = **{summary['avg_coverage_pct']:.1f}%**"
        )
    lines.append("- Per-layer averages:")
    lines.append(
        f"  - overlay Known: **{summary['avg_overlay_known']:.1f}** "
        "(LLM/codex 填; per-stock)"
    )
    lines.append(
        f"  - overlay Optionality: **{summary['avg_overlay_opt']:.1f}**"
    )
    lines.append(
        f"  - realtime injected: **{summary['avg_realtime']:.1f}** "
        "(Tushare/FMP/Futu/akshare)"
    )
    lines.append(
        f"  - L0 inherit (Known industry rows): **{summary['avg_l0_inherit']:.1f}**"
    )
    lines.append(
        f"- With ≥1 realtime value: **{summary['with_any_realtime']}** / "
        f"with zero: **{summary['with_zero_realtime']}**"
    )
    lines.append("")
    lines.append("| Market | Total | With realtime | Coverage |")
    lines.append("|---|---:|---:|---:|")
    for mkt in ("A", "HK", "US", "?"):
        t = summary["by_market"].get(mkt, 0)
        f = summary["by_market_filled"].get(mkt, 0)
        if t:
            lines.append(f"| {mkt} | {t} | {f} | {100*f//t}% |")
    lines.append("")

    # === Coverage Distribution =============================================
    lines.append("## Coverage Distribution")
    lines.append("")
    b = summary["buckets"]
    lines.append(f"- effective ≥ 50: **{b['ge_50']}** stocks")
    lines.append(f"- effective 40–49: **{b['ge_40']}**")
    lines.append(f"- effective 30–39: **{b['ge_30']}**")
    lines.append(f"- effective 20–29: **{b['ge_20']}**")
    lines.append(f"- effective < 20: **{b['lt_20']}**")
    lines.append("")

    # === Per-Industry Aggregates ===========================================
    lines.append("## Per-Industry Aggregates")
    lines.append("")
    lines.append(
        "| Industry | Stocks | overlay K avg | overlay Opt avg | "
        "realtime avg | L0 inherit | effective avg | best (ts, eff) | "
        "worst (ts, eff) |"
    )
    lines.append("|---|---:|---:|---:|---:|---:|---:|---|---|")
    for r in summary["industry_rollup"]:
        lines.append(
            f"| {r['industry_id']} | {r['stocks']} | "
            f"{r['avg_overlay_known']:.1f} | {r['avg_overlay_opt']:.1f} | "
            f"{r['avg_realtime']:.1f} | {r['avg_l0_inherit']:.1f} | "
            f"{r['avg_effective']:.1f} | "
            f"`{r['best_ts']}` ({r['best_effective']}) | "
            f"`{r['worst_ts']}` ({r['worst_effective']}) |"
        )
    lines.append("")

    # === Top sources contributing realtime dp_ids ==========================
    lines.append("## Top sources contributing realtime dp_ids")
    lines.append("")
    lines.append("| source | total rows | unique dp_ids | example dp_id |")
    lines.append("|---|---:|---:|---|")
    # Source rollup sorted by unique dp count desc, then rows desc.
    src_items = sorted(
        summary["source_rollup"].items(),
        key=lambda kv: (-kv[1]["unique_dp_ids"], -kv[1]["rows"]),
    )
    for name, info in src_items:
        lines.append(
            f"| `{name}` | {info['rows']} | {info['unique_dp_ids']} | "
            f"`{info['example']}` |"
        )
    lines.append("")

    # === Layer dp_id lists (kept for back-compat with old readers) ========
    lines.append(
        f"## Layer 1: overlay schema dp_ids "
        f"({len(summary['all_schema_dp_ids'])} unique across all companies)"
    )
    lines.append("")
    lines.append(
        "LLM-derived slots — codex fills these; data sources cannot. "
        "Each company has ~33 of these in its primary overlay."
    )
    lines.append("")
    for dp in summary["all_schema_dp_ids"]:
        lines.append(f"- `{dp}`")
    lines.append("")

    lines.append(
        f"## Layer 2: realtime dp_ids "
        f"({len(summary['all_realtime_dp_ids'])} unique across all companies)"
    )
    lines.append("")
    lines.append(
        "Data points actually written by collector (`realtime_current`). "
        "Exposed via the `realtime` field of `/api/project-ult/stock-overlay`."
    )
    lines.append("")
    for dp in summary["all_realtime_dp_ids"]:
        lines.append(f"- `{dp}`")
    lines.append("")

    lines.append(
        f"## Layer 3: L0 inherit dp_ids "
        f"({len(summary['all_l0_inherit_dp_ids'])} unique across all industries)"
    )
    lines.append("")
    lines.append(
        "`Known` industry-level rows from `config/industry_overlays/*.yaml`. "
        "Shared by every stock in an industry; not stored per-company."
    )
    lines.append("")
    for dp in summary["all_l0_inherit_dp_ids"]:
        lines.append(f"- `{dp}`")
    lines.append("")

    # === Per-Stock Detail ==================================================
    lines.append("## Per-Stock Detail")
    lines.append("")
    if detailed:
        lines.append(
            "| ts_code | name | market | industry | overlay K | overlay Opt | "
            "overlay Unk | realtime | L0 inh | effective | spec % | top sources |"
        )
        lines.append("|---|---|---|---|---:|---:|---:|---:|---:|---:|---:|---|")
    else:
        lines.append(
            "| ts_code | name | market | industry | overlay K | overlay Opt | "
            "realtime | L0 inh | effective | spec % |"
        )
        lines.append("|---|---|---|---|---:|---:|---:|---:|---:|---:|")
    for a in audits:
        if detailed:
            srcs = ", ".join(
                f"{k}:{v}"
                for k, v in sorted(
                    a.realtime_by_source.items(), key=lambda kv: -kv[1]
                )[:3]
            )
            lines.append(
                f"| `{a.ts_code}` | {a.name or '—'} | {a.market} | "
                f"{a.industry_id} | {a.overlay_known} | {a.overlay_optionality} | "
                f"{a.overlay_unknown_real} | {a.realtime_dps} | "
                f"{a.industry_l0_known} | {a.effective_dps} | "
                f"{a.coverage_pct:.1f}% | {srcs} |"
            )
        else:
            lines.append(
                f"| `{a.ts_code}` | {a.name or '—'} | {a.market} | "
                f"{a.industry_id} | {a.overlay_known} | {a.overlay_optionality} | "
                f"{a.realtime_dps} | {a.industry_l0_known} | "
                f"{a.effective_dps} | {a.coverage_pct:.1f}% |"
            )
    lines.append("")

    # === Companies with zero realtime (full list) =========================
    zero = [a for a in audits if not a.realtime_dps]
    if zero:
        lines.append(f"## Companies with zero realtime values ({len(zero)})")
        lines.append("")
        lines.append(
            "These need source attention — collector may be skipping them "
            "(permissions / suspended / unknown ticker mapping)."
        )
        lines.append("")
        lines.append("| ts_code | market | name | industry |")
        lines.append("|---|---|---|---|")
        for a in zero:
            lines.append(
                f"| `{a.ts_code}` | {a.market} | {a.name or '—'} | "
                f"{a.industry_id} |"
            )
        lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")


def write_csv(audits: list[CompanyAudit], out_path: Path) -> None:
    """Write the per-company three-layer CSV.

    Columns are the new canonical set described in the U3 brief; legacy
    readers should switch to ``effective_dps`` / ``coverage_pct``.
    """

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow([
            "ts_code", "name", "market", "industry_ids",
            "overlay_total",
            "overlay_known", "overlay_optionality",
            "overlay_unknown", "overlay_inactive", "overlay_na",
            "realtime_dps", "industry_l0_known",
            "effective_dps", "spec_total", "spec_coverage_pct",
            "realtime_by_source",
            "overlay_known_dp_ids", "overlay_opt_dp_ids",
            "realtime_dp_ids", "industry_l0_dp_ids",
        ])
        for a in audits:
            w.writerow([
                a.ts_code, a.name or "", a.market,
                "|".join(a.industry_ids),
                a.overlay_total,
                a.overlay_known, a.overlay_optionality,
                a.overlay_unknown_real, a.overlay_inactive, a.overlay_na,
                a.realtime_dps, a.industry_l0_known,
                a.effective_dps, a.spec_total,
                f"{a.coverage_pct:.2f}",
                json.dumps(a.realtime_by_source, ensure_ascii=False),
                ";".join(a.overlay_known_dp_ids),
                ";".join(a.overlay_opt_dp_ids),
                ";".join(a.realtime_dp_ids),
                ";".join(a.industry_l0_dp_ids),
            ])
